version: '3.3'

volumes:
  - haproxy
  - config
  
services:
  haproxy:
    image: haproxy:lts-bookworm
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - 80:80
      - 443:443
      - 8443:8443
      - 53:53
      - 953:953
    volumes:
      - haproxy:/var/lib/haproxy
      - config:/usr/local/etc/haproxy/